//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carritoPrestamo
    {
        public int idCarritoPrestamo { get; set; }
        public Nullable<System.DateTime> fechaPrestamo { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public int idCliente { get; set; }
        public int idTipoPrestamo { get; set; }
        public int idEmpleado { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> idLibro { get; set; }
    
        public virtual Libro Libro { get; set; }
    }
}
