//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checada
    {
        public int idChecada { get; set; }
        public Nullable<System.TimeSpan> entradaChecada { get; set; }
        public Nullable<System.TimeSpan> salidaChecada { get; set; }
        public int idEmpleado { get; set; }
        public Nullable<System.DateTime> fecha_es { get; set; }
    
        public virtual Empleado Empleado { get; set; }

        internal bool ToString(string v)
        {
            throw new NotImplementedException();
        }
    }
}
