//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Prestamoes = new HashSet<Prestamo>();
            this.Ventas = new HashSet<Venta>();
        }
    
        public int idCliente { get; set; }
        public string nombresCliente { get; set; }
        public string apellidoPCliente { get; set; }
        public string apellidoMCliente { get; set; }
        public Nullable<System.DateTime> fechaNacimientoCliente { get; set; }
        public string telefonoCliente { get; set; }
        public string direccionCliente { get; set; }
        public string usuarioCliente { get; set; }
        public string contraseñaCliente { get; set; }
        public Nullable<int> Activos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
