//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Checadas = new HashSet<Checada>();
            this.Prestamoes = new HashSet<Prestamo>();
            this.Ventas = new HashSet<Venta>();
        }
    
        public int idEmpleado { get; set; }
        public string nombresEmpleado { get; set; }
        public string apellidoPEmpleado { get; set; }
        public string apellidoMEmpleado { get; set; }
        public string direccionEmpleado { get; set; }
        public string telefonoEmpleado { get; set; }
        public int idHorario { get; set; }
        public Nullable<int> Activos { get; set; }
        public string usuarioEmp { get; set; }
        public string contraseñaEmp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checada> Checadas { get; set; }
        public virtual Horario Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
